/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const slope: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const aspect_degrees: (a: number, b: number) => [number, number, number, number];
export const hillshade_compute: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const multidirectional_hillshade: (a: number, b: number) => [number, number, number, number];
export const curvature_compute: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const tpi_compute: (a: number, b: number, c: number) => [number, number, number, number];
export const tri_compute: (a: number, b: number) => [number, number, number, number];
export const twi_compute: (a: number, b: number) => [number, number, number, number];
export const geomorphons_compute: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const northness_compute: (a: number, b: number) => [number, number, number, number];
export const eastness_compute: (a: number, b: number) => [number, number, number, number];
export const dev_compute: (a: number, b: number, c: number) => [number, number, number, number];
export const shape_index: (a: number, b: number) => [number, number, number, number];
export const curvedness: (a: number, b: number) => [number, number, number, number];
export const sky_view_factor: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const uncertainty_slope: (a: number, b: number, c: number) => [number, number, number, number];
export const ssa_2d_denoise: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const fill_depressions: (a: number, b: number) => [number, number, number, number];
export const priority_flood_fill: (a: number, b: number) => [number, number, number, number];
export const flow_direction_d8: (a: number, b: number) => [number, number, number, number];
export const flow_accumulation_d8: (a: number, b: number) => [number, number, number, number];
export const hand_compute: (a: number, b: number, c: number) => [number, number, number, number];
export const ndvi: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const ndwi: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const savi: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const normalized_diff: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const morph_erode: (a: number, b: number, c: number) => [number, number, number, number];
export const morph_dilate: (a: number, b: number, c: number) => [number, number, number, number];
export const morph_opening: (a: number, b: number, c: number) => [number, number, number, number];
export const morph_closing: (a: number, b: number, c: number) => [number, number, number, number];
export const focal_mean: (a: number, b: number, c: number) => [number, number, number, number];
export const focal_std: (a: number, b: number, c: number) => [number, number, number, number];
export const focal_range: (a: number, b: number, c: number) => [number, number, number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
